# Build and deploy to GitHub Pages
name: Deploy to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Check API Key
        run: |
          if [ -z "$API_KEY" ]; then
            echo "❌ API_KEY is not set or empty"
            echo "Make sure you have added API_KEY to repository secrets"
            exit 1
          else
            echo "✅ API_KEY is set"
          fi
        env:
          API_KEY: ${{ secrets.API_KEY }}
      
      - name: Build
        run: npm run build
        env:
          API_KEY: ${{ secrets.API_KEY }}
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
